/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'holiday' at '16-7-8 下午10:53' with Gradle 2.12
 *
 * @author holiday, @date 16-7-8 下午10:53
 */
class Test {

    public static void main(String[] args) {
	println("pansijing")
    }
    boolean someLibraryMethod() {
        true
    }
}
