/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'holiday' at '16-7-8 下午10:42' with Gradle 2.12
 *
 * @author holiday, @date 16-7-8 下午10:42
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
